export const IPC = {
  DB_INITIALIZE: 'db:initialize',
  DB_LOAD_CONTACTS: 'db:load-contacts',
  DB_LOAD_SESSIONS: 'db:load-sessions',
  DB_LOAD_MESSAGES: 'db:load-messages',
  DB_GET_KEY_STATUS: 'db:get-key-status',
  DB_EXTRACT_KEYS: 'db:extract-keys',
  DB_IMPORT_KEY: 'db:import-key',

  API_GET_UUID: 'api:get-uuid',
  API_GET_QR_CODE: 'api:get-qr-code',
  API_POLL_LOGIN: 'api:poll-login',
  API_COMPLETE_LOGIN: 'api:complete-login',
  API_INIT: 'api:init',
  API_GET_CONTACTS: 'api:get-contacts',
  API_SEND_TEXT: 'api:send-text',
  API_SEND_IMAGE: 'api:send-image',
  API_SEND_FILE: 'api:send-file',
  API_GET_IMAGE: 'api:get-image',
  API_GET_AVATAR: 'api:get-avatar',
  API_LOGOUT: 'api:logout',
  API_START_SYNC: 'api:start-sync',
  API_RESTORE_SESSION: 'api:restore-session',

  ON_NEW_MESSAGES: 'event:new-messages',
  ON_CONTACT_UPDATE: 'event:contact-update',
  ON_LOGIN_STATE_CHANGE: 'event:login-state',
  ON_SESSION_STATE_UPDATE: 'event:session-state',
  ON_SYNC_ERROR: 'event:sync-error',

  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  SETTINGS_GET_ALL: 'settings:get-all',
  SETTINGS_RESET: 'settings:reset',

  SYSTEM_OPEN_PATH: 'system:open-path',
  SYSTEM_OPEN_FILE_DIALOG: 'system:open-file-dialog',
  SYSTEM_SAVE_DIALOG: 'system:save-dialog',
  SYSTEM_CAPTURE_SCREENSHOT: 'system:capture-screenshot',
  SYSTEM_CLIPBOARD_WRITE: 'system:clipboard-write',
  SYSTEM_GET_PLATFORM: 'system:get-platform',
  SYSTEM_OPEN_SETTINGS_WINDOW: 'system:open-settings-window',
  SYSTEM_GET_DB_PATH: 'system:get-db-path',
  SYSTEM_GET_DB_SIZES: 'system:get-db-sizes',

  MOMENTS_REFRESH: 'moments:refresh',
  MOMENTS_ADD_POST: 'moments:add-post',
  MOMENTS_TOGGLE_LIKE: 'moments:toggle-like',
  MOMENTS_ADD_COMMENT: 'moments:add-comment',

  DB_GLOBAL_SEARCH: 'db:global-search',
  DB_EXPORT_CHAT: 'db:export-chat',
  DB_LOAD_HIDDEN_SESSIONS: 'db:load-hidden-sessions',
  DB_LOAD_MORE_MESSAGES: 'db:load-more-messages',
  DB_LOAD_ALL_MESSAGES: 'db:load-all-messages',
  DB_GET_CALL_HISTORY: 'db:get-call-history',

  FAVORITES_STAR: 'favorites:star',
  FAVORITES_UNSTAR: 'favorites:unstar',
  FAVORITES_GET: 'favorites:get',

  PLUGIN_LIST: 'plugin:list',
  PLUGIN_LOAD: 'plugin:load',
  PLUGIN_UNLOAD: 'plugin:unload',
  PLUGIN_RELOAD: 'plugin:reload',
  PLUGIN_ENABLE: 'plugin:enable',
  PLUGIN_DELETE: 'plugin:delete',
  PLUGIN_CREATE: 'plugin:create',
  PLUGIN_INSTALL: 'plugin:install',
  PLUGIN_GET_INFO: 'plugin:get-info',
  PLUGIN_RUN_CODE: 'plugin:run-code',
  PLUGIN_EXEC: 'plugin:exec',
  PLUGIN_GET_DIR: 'plugin:get-dir',

  FILE_OPEN_LOCAL: 'file:open-local',
  FILE_SAVE_ATTACHMENT: 'file:save-attachment',
  FILE_RESOLVE_PATH: 'file:resolve-path',
  FILE_READ_VIDEO_THUMB: 'file:read-video-thumb',
} as const
